# Pry.commands.alias_command 'c', 'continue'
# Pry.commands.alias_command 's', 'step'
Pry.commands.alias_command 'p', 'play -l'

    Pry.commands.alias_command 't', 'show-stack'
    Pry.commands.alias_command 's', 'step'
    Pry.commands.alias_command 'n', 'next'
    Pry.commands.alias_command 'c', 'continue'
    Pry.commands.alias_command 'f', 'finish'
    Pry.commands.alias_command 'u', 'up'
    Pry.commands.alias_command 'd', 'down'
    Pry.commands.alias_command 'b', 'break'
    Pry.commands.alias_command 'w', 'whereami'
